language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y libmaxminddb-dev libssl-dev
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - git clone https://git.kore.io/kore.git
  - cd kore && make NOTLS=1
  - sudo make install
  - cd -

script: kodev build

env:
  global:
    - secure: "DYiX2BTl9/Cb2HexzubmBtLw6vyQKn15MI40AU5/5cSJie57TXnxdcalmiodUnikLYdbDiqmbVTKChsyj4IssEMxZxeVoiNdjb2ILVcZSixV7VVQr1fHp+oyAgHI5CsQS9BqyU4chJdM65kTQvg9cGCG1BfuCR4GGVtbGUnAH2o="

addons:
  coverity_scan:
    project:
      name: "fcambus/telize"
      version: 2.0.0
      description: "High performance JSON IP and GeoIP REST API (IP Geolocation)"
    notification_email: fred@statdns.com
    build_command: kodev build
    branch_pattern: master
